# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


champions = Champion.create([
              { name: 'Ahri' },
              { name: 'Akali' },
              { name: 'Alistar' },
              { name: 'Amumu' },
              { name: 'Anivia' },
              { name: 'Annie' },
              { name: 'Ashe' },
              { name: 'Blitzcrank' },
              { name: 'Brand' },
              { name: 'Caitlyn' },
              { name: 'Cassiopeia' },
              { name: 'Cho\'Gath' },
              { name: 'Corki' },
              { name: 'Darius' },
              { name: 'Diana' },
              { name: 'Dr. Mundo' },
              { name: 'Draven' },
              { name: 'Elise' },
              { name: 'Evelynn' },
              { name: 'Ezreal' },
              { name: 'Fiddlesticks' },
              { name: 'Fiora' },
              { name: 'Fizz' },
              { name: 'Galio' },
              { name: 'Gangplank' },
              { name: 'Garen' },
              { name: 'Gragas' },
              { name: 'Graves' },
              { name: 'Hecarim' },
              { name: 'Heimerdinger' },
              { name: 'Irelia' },
              { name: 'Janna' },
              { name: 'Jarvan IV' },
              { name: 'Jax' },
              { name: 'Jayce' },
              { name: 'Karma' },
              { name: 'Karthus' },
              { name: 'Kassadin' },
              { name: 'Katarina' },
              { name: 'Kayle' },
              { name: 'Kennen' },
              { name: 'Kha\'Zix' },
              { name: 'Kog\'Maw' },
              { name: 'LeBlanc' },
              { name: 'Lee Sin' },
              { name: 'Leona' },
              { name: 'Lulu' },
              { name: 'Lux' },
              { name: 'Malphite' },
              { name: 'Malzahar' },
              { name: 'Maokai' },
              { name: 'Master Yi' },
              { name: 'Miss Fortune' },
              { name: 'Mordekaiser' },
              { name: 'Morgana' },
              { name: 'Nami' },
              { name: 'Nasus' },
              { name: 'Nautilus' },
              { name: 'Nidalee' },
              { name: 'Nocturne' },
              { name: 'Nunu' },
              { name: 'Olaf' },
              { name: 'Orianna' },
              { name: 'Pantheon' },
              { name: 'Poppy' },
              { name: 'Rammus' },
              { name: 'Renekton' },
              { name: 'Rengar' },
              { name: 'Riven' },
              { name: 'Rumble' },
              { name: 'Ryze' },
              { name: 'Sejuani' },
              { name: 'Shaco' },
              { name: 'Shen' },
              { name: 'Shyvana' },
              { name: 'Singed' },
              { name: 'Sion' },
              { name: 'Sivir' },
              { name: 'Skarner' },
              { name: 'Sona' },
              { name: 'Soraka' },
              { name: 'Swain' },
              { name: 'Syndra' },
              { name: 'Talon' },
              { name: 'Taric' },
              { name: 'Teemo' },
              { name: 'Tristana' },
              { name: 'Trundle' },
              { name: 'Tryndamere' },
              { name: 'Twisted Fate' },
              { name: 'Twitch' },
              { name: 'Udyr' },
              { name: 'Urgot' },
              { name: 'Varus' },
              { name: 'Vayne' },
              { name: 'Veigar' },
              { name: 'Vi' },
              { name: 'Viktor' },
              { name: 'Vladimir' },
              { name: 'Volibear' },
              { name: 'Warwick' },
              { name: 'Wukong' },
              { name: 'Xerath' },
              { name: 'Xin Zhao' },
              { name: 'Yorick' },
              { name: 'Zed' },
              { name: 'Ziggs' },
              { name: 'Zilean' },
              { name: 'Zyra' }
            ])
